pipeline:
  prepare:
    image: golang:1.10-alpine
    commands:
    - apk add --update --no-cache git curl
    - curl -fsSL -o dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
    - chmod +x dep
    - curl -fsSL -o cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    - chmod +x ./cc-test-reporter

  test:
    image: golang:1.10-alpine
    commands:
    - apk add --update --no-cache git
    - go install
    - go test

  build_ssm_binary:
    image: golang:alpine
    commands:
    - apk add --no-cache git
    - go get -v github.com/SPSCommerce/go-ssm-get-parameter
    - cp $GOPATH/bin/go-ssm-get-parameter .
    when:
      event:
      - tag

  docker-build:
    image: spscommerce/plugin-ecr
    account: 333808835704
    repo: plugin-chartmuseum
    tags:
      - ${DRONE_TAG}
      - latest
    when:
      event: [ tag ]
